config/routes.rb
SitepointYtVideos::Application.routes.draw do
  resources :videos, only: [:index, :new, :create]
  root to: 'videos#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @style = params[:selected]
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def roulette
        #initialize Youtube_it
        client = YouTubeIt::OAuth2Client.new(dev_key: ENV['YT_DEV'])
        
        #calling query and generating random integer based on total number of results.
        response = client.videos_by(:query => (@style? "#{@style}" : "'dance'"), :user => 'stanceelements')
        randnum = rand(0..49)
        x = response.total_result_count-49
        #randnum cannot be over 450. Youtube will not return more than 500 queries
        maxnum = 450
        if x > maxnum
            x = maxnum
        end
        randoffset = rand(0..x)
        if @style.nil?
        else
            randoffset = rand(0..450)
        end
        
        #search query with random offset. to maximize search result, we have to use offset, because Youtube only returns a maximum of 50 results per query, but you have access to at least 500.
        response = client.videos_by(:query => (@style? "#{@style}" : "'dance', :user => 'stanceelements'"), :offset => randoffset, :max_results => 50,)
        logger.debug "randoffset is: #{randoffset}"
        
        #pick a random video from the search results and get its info
        video = response.videos[randnum]
        youtube_id = video.unique_id
        @youtube_id = youtube_id
        @title = video.title
        @author = video.author.name
        
        #check if there are ratings
        if video.rating.nil?
            @likes = 0
            @dislikes = 0
        else
            @likes = number_with_delimiter(video.rating.likes, :delimiter => ',')
            @dislikes = number_with_delimiter(video.rating.dislikes, :delimiter => ',')
        end
        @views = number_with_delimiter(video.view_count, :delimiter => ',')
        date_time = video.published_at
        @date = date_time.strftime("%b %d, %Y")
        
        #comment section
        @comment_count = video.comment_count
        comments = "https://gdata.youtube.com/feeds/api/videos/#{youtube_id}/comments?max-results=50&alt=json&prettyprint=true"
        all_comments = JSON.load(open(comments))
        feed = all_comments['feed']
        @entry = feed['entry']
        
        #uploader thumbnail
        uploader_id = video.author.uri
        uploader = JSON.load(open("#{uploader_id}?alt=json"))
        @uploader_thumb = uploader['entry']['media$thumbnail']['url']
        
        
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Style Roulette</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-60580538-1', 'auto');
    ga('send', 'pageview');
  </script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://www.google.com/jsapi" type="text/javascript"></script>
  <script src="https://www.youtube.com/iframe_api"></script>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= yield %>
    <div id="footer">
      <div class="container">
      </div>
    </div>
  </body>
</html>

app/views/partials/_mainview.html.erb
<br>
<div class="row">
    <div class="col-sm-12">
      <% roulette %>
      <div class="row">
        <div class="col-sm-2 hidden-xs" id="thumb-col"><%= raw("<img src='#{@uploader_thumb}' />") %></div>
        <div class="col-sm-10">
          <h4><b><%= @title.titleize %></b></h4>
          <p class="caption">by <b><%= @author %></b> on <%= @date %> <b>&middot;</b> <b><%= @views %></b> views
          <span class="hidden-xs"><b>&middot;</b>
            <span class="like"><span class='glyphicon glyphicon glyphicon-thumbs-up'></span> <%= @likes %> </span> 
            <span class="dislike"><span class='glyphicon glyphicon glyphicon-thumbs-down dislike'></span> <%= @dislikes %></span>
          </span></p>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-9">
          <div class="embed-container">
            <%= content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{@youtube_id}?autoplay=1&autohide=1&color=white&controls=2&iv_load_policy=3&modestbranding=1&showinfo=0&theme=light") %>
          </div>
          <div class="row">
            <div class="col-xs-12" id="next_a">
              <div>
                <a href="#" onclick='location.reload(true); return false;' >
                  <div id="next_button">
                  <div style="margin-left: auto; margin-right: auto;"><h1>Next <i class="fa fa-hand-o-right"></i></h1></div>
                  </div>
                </a>
              </div>
              <br>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div id="comment_title"><h4 style="margin-top: 10px;"><i class="fa fa-comments"></i>  <%= pluralize(@comment_count, 'comment') %></h3></div>
          <br>
          <div id="comments">
            <% if @entry.nil? %>
              <div><h5>No comments here</h5></div>
              <% else %>
              <% @entry.map do |n| %>
                <% post = n.select{|x| x['content']} %>
                <% user = n.select{|x| x['author']} %>
                <% replycount = n.select{|x| x['yt$replyCount']} %>
                <div>
                  <b class="caption"><%= user['author'][0]['name']['$t'] %>:</b> <%= post['content']['$t'] %>
                </div>
                <!--<div>
                  <%= replycount['yt$replyCount']['$t'] %>
                </div>-->
                <br>
              <% end %>
            <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/videos/_choose.html.erb
<div class="form-group">
  <%= form_tag videos_path, :method => 'get', :name => "selectstyle", :remote => true do %>
    <div>
        <%= select_tag(:selected, options_for_select({"Style" => " ", "bboying" =>"bboy", "tricking" => "tricking", "popping" => "popping dance", "tutting" => "tutting dance", "locking" => "locking dance", "house" => "house dance dancing", "hip hop" => "hip hop dance", "street dance" => "street dance", "freestyle" => "freestyle dance", "old school" => "old school dance", "footwork" => "footwork dance", "waacking" => "waacking", "krumping" => "krumping", "salsa" => "salsa dance", "ghetto" => "ghetto dance", "twerking" => "twerking", "pole" => "pole dancing", "all random" => "dancing"}, selected: :option), :onchange => ("javascript: document.selectstyle.submit();"), :class => "selectpicker") %>
    </div>
  <% end %>
</div>

app/views/videos/new.html.erb
<%= render partial: "choose" %>
  
<h1>New video</h1>

  <%= form_for @video do |f| %>
    <%= render 'shared/errors', object: @video %>

    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>

    <%= f.submit class: 'btn btn-default' %>
  <% end %> 
</div>